### ISSUE TITLE
Call tu undefined function Utils\report_batch_operation_results

### ISSUE THREAD

**Issue by nasri-lab** [wp-cli/widget-command#55]
I am using wp cli php library and this class Widget-command is thrwing an error when calling : 

Utils\report_batch_operation_results( 'widget', 'delete', count( $args ), $count, $errors );

The exact error is :
PHP Fatal error:  Uncaught Error: Call to undefined function WP_CLI\Utils\report_batch_operation_results() in ...\vendor\wp-cli\widget-command\src\Widget_Command.php:364

I do have the Util namespace, with the function report_batch_operation_results, I suspect the call to the namespace which may cause the issue.

Could you check please and inform me.

**Comment by danielbachhuber** [comment]
Hey @XNUMERIK,

Thanks for the report!

It's hard to say what the issue might be without access to the full underlying code. Feel free to stop by the `#cli` channel on [WordPress.org](https://make.wordpress.org/chat/) Slack if you'd like help debugging further.
